#.travis.yml

language: node_js
node_js:
  - "10.0.0"
 
dist: trusty # needs Ubuntu Trusty
sudo: required

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - npm run test --watch=false && npm run e2e

after_success:
  - ng build --prod && firebase deploy --token $FIREBASE_TOKEN --project tqs-go-nutri

#notifications:
#  email:
#    on_failure: change
#    on_success: change

#branches:
#  only:
#    - master
