#.travis.yml

language: node_js
node_js:
  - "10.0.0"
 
dist: trusty # needs Ubuntu Trusty
sudo: required

addons:
  chrome: beta

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

cache:
  directories:
    - node_modules
    
addons:
  sonarcloud:
    organization: "bdomingues-github"
    token:
      secure: $SONAR_TOKEN


before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

script:
  - ng test --code-coverage --watch=false
  - ng e2e
  - ng build --prod
  - sonar-scanner
  
deploy:
  provider: script
  script: npm install && ng build --prod && firebase deploy --token $FIREBASE_TOKEN --project tqs-go-nutri
  on:
    branch: master

#deploy:
#  provider: heroku
#  api_key:
#    secure: $HEROKU_KEY
#  app: tqsnutri
#  on:
#    repo: tqs18-g205/webapp

#notifications:
#  email:
#    on_failure: change
#    on_success: change

#branches:
#  only:
#    - master
